/**
 * Browser-side API + route constants.
 *
 * `BASE_URL` resolves Vite env vars (`VITE_API_BASE_URL`) at build time
 * and falls back to a sensible local/prod default. The actual list of
 * endpoint URLs is generated by `createApiPaths()` in
 * `@time2leave/shared` so the mobile client emits exactly the same
 * shapes from its own base URL.
 */
import { createApiPaths } from "@time2leave/shared";

const DEFAULT_DEV_BASE_URL = "http://localhost:8000";
const DEFAULT_PROD_BASE_URL = "https://api.time2leave.com";

const envBase = import.meta.env.VITE_API_BASE_URL as string | undefined;
export const BASE_URL =
    envBase && envBase.length > 0
        ? envBase
        : import.meta.env.DEV
          ? DEFAULT_DEV_BASE_URL
          : DEFAULT_PROD_BASE_URL;

export const API = createApiPaths(BASE_URL);

export const ROUTES = {
    splash: "/",
    trips: "/trips",
    newTrip: "/trips/new",
    trip: (id: string) => `/trips/${id}`,
    settings: "/settings",
    adminAllowlist: "/admin/allowlist",
    // Public legal / contact pages. Both are required for App Store
    // Connect submission (Support URL and Privacy Policy URL) and
    // must resolve without authentication so App Review can verify
    // them on a clean browser session.
    support: "/support",
    privacy: "/privacy",
} as const;
